---
#cluster-cancel: "scancel"
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --account pezzar-lab
    --mail-type FAIL
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --job-name=smk-{rule}-{wildcards}-%j
    --output=logs/{rule}/%j.out
use-envmodules: "True"
restart-times: "1"
max-jobs-per-second: "20"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "60"
use-conda: "False"
use-singularity: "False"
jobs: "100"
printshellcmds: "True"
keep-going: "True"
cluster-status: "status-sacct.sh"


# For help on slurm variables and conventions see: https://slurm.schedmd.com/sbatch.html
# In YAML the hyphen indicate the start the item in a list.
# For example:
# a:
#   - b: c1
#     d: e1
#   - d: e2
#     b: c2
# here "a" is a list that contains 2 intems (each item is a dictionary)
default-resources:
  - runtime="1hour" # Slurm format is (among others) hours:minutes:seconds. Check https://slurm.schedmd.com/sbatch.html for more
  - mem_mb=2000
  - disk_mb=1000000
  - partition="serial"
  # Aparently threads need to be declared in each rule...
set-threads:
  - align_fastq=12
  - dedup_bam=1 # Apparently markdup is not multithreaded, and if not piping then 1 thread should do it
  - filter_spiked_in_bam_int_genome=8 # Sambamba view
  - filter_spiked_in_bam_spike_in_genome=8 # Sambamba
  - filter_bam=8 # Sambamba view
  - create_coverage_bw=12 # Check
  - get_strand_sep_pe_bams=2
  - clip_1bp_PE=2
  - clip_1bp_SR=2
  - get_strand_sep_sr_bams=2
  - call_peaks_macs2=2
  - crosscorrelation=2
  - dros_normalization=12
  - trim_adapters_SE=6
  - trim_adapters_PE=6
  - trim_adaptase=4
# set-resources: map rule names to resources in general
set-resources:
  # Memory (MBs)
  # - align_fastq:mem_mb=40000

  # Run time (hours:minutes:seconds)
  # - align_fastq:runtime="05:00:00"
