---
executor: slurm
default-resources:
  slurm_account: "pezzar-lab"
  slurm_partition: "serial"
  slurm_extra: "f'--mail-type FAIL'"
  runtime: "10h"
  mem_mb: "2000"
use-envmodules: "True"
restart-times: "1"
max-jobs-per-second: "20"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "60"
use-conda: "False"
use-singularity: "False"
jobs: "100"
printshellcmds: "True"
keep-going: "True"

set-threads:
  - align_fastq=12
  - annotate_peaks=1
  - call_peaks_macs2=2
  - clip_1bp=2
  - compute_matrix_outfiles_hs=1
  - create_coverage_bw=12 # Check
  - crosscorrelation=2
  - dedup_bam=1 # Apparently markdup is not multithreaded, and if not piping then 1 thread should do it
  - dros_normalization=12
  - dros_normalization_report=1
  - filter_peaks_blk_grey_list=1
  - filter_spiked_in_bam_int_genome=8 # Sambamba view
  - filter_spiked_in_bam_spike_in_genome=8 # Sambamba
  - filter_bam=8 # Sambamba view
  - FRIP=1
  - get_strand_sep_pe_bams=2
  - get_strand_sep_sr_bams=2
  - index=2
  - insert_size_picard=2
  - intersect_peaks_HSs_list=1
  - library_complexity_picard=2
  - markdown_report_aggregate_profiles=1
  - merge_bams=2
  - merge_watson_or_crick=2
  - modify_annotated_peaks=1
  - multiqc=2
  - process_aggregate_profiles=1
  - process_aggregate_profiles_clipped=1
  - plot_heatmaps=1
  - samtools_flagstat=2
  - samstats=2
  - sumarize_peak_count=1
  - trim_adapters_SE=6
  - trim_adapters_PE=6
  - trim_adaptase=4
  - wrangle_X_nonPAR_asymmetric_HS=1

set-resources:
    align_fastq:
      mem_mb: f"{21000 + (attempt-1) * 10000}"
      runtime: f"{max(((input.size_mb - 1900) / 50) * attempt, 150)}min"
    annotate_peaks:
      mem_mb: f"{ 6000 * attempt }"
    call_peaks_macs2:
      mem_mb: f"{ 7000 * attempt }"
    clip_1bp:
      mem_mb: f"{1900 + (attempt - 1) * 1000}"
    compute_matrix_outfiles_hs:
      mem_mb: f"{ 3000 * attempt }"
    create_coverage_bw:
      mem_mb: f"{8000 + (1 - attempt) * 4000}"
    crosscorrelation:
      mem_mb: f"{  attempt * 7500 }"
    dedup_bam:
      mem_mb: f"{ 5600 * attempt }"
    dros_normalization:
      mem_mb: f"{ 8000 + (1 - attempt) * 4000 }"
    filter_bam:
      mem_mb: f"{ 200 * attempt }"
    filter_spiked_in_bam_int_genome:
      mem_mb: f"{40000 + (attempt-1) * 15000}"
    filter_spiked_in_bam_spike_in_genome:
      mem_mb: f"{40000 + (attempt-1) * 15000}"
    get_strand_sep_bams:
      mem_mb: f"{500 * attempt}"
    index:
      mem_mb: f"{350 * attempt}"
    insert_size_picard:
      mem_mb: f"{ 300 * attempt }"
    library_complexity_picard:
      mem_mb: f"{ int(input.size_mb * 0.5 + 4100 + (attempt - 1) * 2000) }"
    merge_bams:
      mem_mb: f"{ 160 * attempt }"
    merge_watson_or_crick:
      mem_mb: f"{ 350 * attempt }"
    multiqc:
      mem_mb: f"{ 400 * attempt }"
    process_aggregate_profiles:
      mem_mb: f"{ int(input.size_mb + 1000) }"
    samstats:
      mem_mb: f"{ 210 + (attempt-1) * 100 }"
    samtools_flagstat:
      mem_mb: f"{ 210 + (attempt-1) * 100 }"
    trim_adaptase:
      mem_mb: f"{400 * attempt}"
    trim_adapters_SE:
      mem_mb: f"{3500 * attempt}"
    trim_adapters_PE:
      mem_mb: f"{3700 * attempt}"

# For help on slurm variables and conventions see: https://slurm.schedmd.com/sbatch.html
# In YAML the hyphen indicate the start the item in a list.
# For example:
# a:
#   - b: c1
#     d: e1
#   - d: e2
#     b: c2
# here "a" is a list that contains 2 intems (each item is a dictionary)
