---
#cluster-cancel: "scancel"
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --account pezzar-lab
    --mail-type FAIL
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --job-name=smk-{rule}-{wildcards}-%j
    --output=logs/{rule}/%j.out
use-envmodules: "True"
restart-times: "0"
max-jobs-per-second: "20"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "60"
use-conda: "False"
use-singularity: "False"
jobs: "100"
printshellcmds: "True"
keep-going: "True"

#--output {log}_SLURM

# For help on slurm variables and conventions see: https://slurm.schedmd.com/sbatch.html
# In YAML the hyphen indicate the start the item in a list.
# For example:
# a:
#   - b: c1
#     d: e1
#   - d: e2
#     b: c2
# here "a" is a list that contains 2 intems (each item is a dictionary)
default-resources:
  - runtime="01:00:00" # Slurm format is (among others) hours:minutes:seconds. Check https://slurm.schedmd.com/sbatch.html for more
  - mem_mb=2000
  - disk_mb=1000000
  - partition="serial"
  # Aparently threads need to be declared in each rule...
set-threads:
  - align_fastq=12
  - dedup_bam=1 # Apparently markdup is not multithreaded, and if not piping then 1 thread should do it
  - filter_spiked_in_bam_int_genome=8 # Sambamba view
  - filter_spiked_in_bam_spike_in_genome=8 # Sambamba
  - filter_bam=8 # Sambamba view
  - create_coverage_bw=12 # Check
  - get_strand_sep_pe_bams=2
  - clip_1bp_PE=2
  - clip_1bp_SR=2
  - get_strand_sep_sr_bams=2
  - call_peaks_macs2=2
  - crosscorrelation=2
  - dros_normalization=12
  - trim_adapters_SE=6
  - trim_adapters_PE=6
  - trim_adaptase=4
# set-resources: map rule names to resources in general
set-resources:
  # Memory (MBs)
  - align_fastq:mem_mb=40000
  - dedup_bam:mem_mb=10000 # Markdup
  - filter_bam:mem_mb=10000 # Sambamba
  - filter_spiked_in_bam_int_genome:mem_mb=40000
  - filter_spiked_in_bam_spike_in_genome:mem_mb=40000
  - create_coverage_bw:mem_mb=15000
  - dros_normalization:mem_mb=15000
  - get_strand_sep_pe_bams:mem_mb=5000
  - clip_1bp_PE:mem_mb=5000
  - clip_1bp_SR:mem_mb=5000
  - get_strand_sep_sr_bams:mem_mb=5000
  - call_peaks_macs2:mem_mb=8000
  - filter_peaks_blk_grey_list:mem_mb=500
  - intersect_peaks_HSs_list:mem_mb=500
  - FRIP_narrow:mem_mb=2000
  - FRIP_broad:mem_mb=2000
  - crosscorrelation:mem_mb=10000
  - library_complexity_picard:mem_mb=10000
  - annotate_peaks:mem_mb=8000 # For some reason this rule seem to need a lot of memory
  - markdown_report_aggregate_profiles:mem_mb=1000
  - trim_adapters_SE:mem_mb=10000
  - trim_adapters_PE:mem_mb=10000
  - trim_adaptase:mem_mb=600
  # Run time (hours:minutes:seconds)
  - align_fastq:runtime="05:00:00"
  - dedup_bam:runtime="02:00:00" # Check
  - filter_bam:runtime="05:00:00"
  - filter_spiked_in_bam_int_genome:runtime="05:00:00"
  - filter_spiked_in_bam_spike_in_genome:runtime="05:00:00"
  - create_coverage_bw:runtime="01:00:00"
  - dros_normalization:runtime="01:00:00"
  - get_strand_sep_pe_bams:runtime="05:00:00"
  - clip_1bp_PE:runtime="05:00:00"
  - clip_1bp_SR:runtime="05:00:00"
  - get_strand_sep_sr_bams:runtime="05:00:00"
  - filter_peaks_blk_grey_list:runtime="00:10:00"
  - intersect_peaks_HSs_list:runtime="00:10:00"
  - FRIP_narrow:runtime="2:00:00"
  - FRIP_broad:runtime="2:00:00"
  - crosscorrelation:runtime="4:00:00"
  - library_complexity_picard:runtime="5:00:00"
  - markdown_report_aggregate_profiles:runtime="0:30:00"
  - trim_adapters_SE:runtime="0:10:00"
  - trim_adapters_PE:runtime="0:10:00"
  - trim_adaptase:runtime="0:10:00"
